### ISSUE TITLE
Php Deprecated Error - jsonSerialize()

### ISSUE THREAD

**Issue by ilearnbydoing** [craftsys/msg91-laravel#14]
Php 8.1
Laravel .80
In Laravel Tinker test 
getting this error

`>>> echo Msg91::otp()::class
PHP Deprecated:  Return type of Craftsys\Msg91\Options::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /MYAPP_PATH/vendor/craftsys/msg91-php/src/Options.php on line 215
Craftsys\Msg91\OTP\OTPService⏎`

**Comment by sudkumar** [comment]
Thanks for reporting. Will test and fix it.
