### ISSUE TITLE
OTP Verification appears to be broken

### ISSUE THREAD

**Issue by ishanAhuja** [craftsys/msg91-laravel#5]
Sending an OTP is working just fine but I'm getting an exception (`Craftsys/Msg91/Exceptions/ResponseErrorException with message 'Invalid authkey'`) when trying to verify the OTP.

Steps to recreate:
* Create a new Laravel 8 project
* Install `msg91-laravel`
* Set the `msg91` key with the appropriate values in `config/services.php`
* In Tinker (`php artisan tinker`), run `Msg91::otp()->to(918888888888)->send();` to receive the OTP. Then run `Msg91::otp(1234)->to(918888888888)->verify();` to verify. The verification statement throws the exception mentioned above.

If there's any other info you may need to recreate the issue, do let me know. Thanks for making this wonderful package (as well as msg91-php) 🤗

**Comment by sudkumar** [comment]
Thanks @ishanAhuja . I will look into it.

**Comment by sudkumar** [comment]
Yes. There is an issue. I will let you know when it is fixed.

**Comment by sudkumar** [comment]
The issue is because of `content-type` for otp verification endpoint. All other apis accept the `application/json` content type but the otp verification endpoint accepts `application/x-www-form-urlencoded`. 😢

**Comment by ishanAhuja** [comment]
Oh 🤦🏽‍♂️

That's a strange design choice, if intentional…

**Comment by sudkumar** [comment]
@ishanAhuja  Feel free to reopen if not working.

**Comment by ishanAhuja** [comment]
Working perfectly now. Thank you so much! 😊

**Comment by sudkumar** [comment]
Thank you for testing. 🍻
