### ISSUE TITLE
OTP Length Support

### ISSUE THREAD

**Issue by teamseamive** [craftsys/msg91-laravel#7]
Any way you could add OTP length support parameter since the default is 4 if someone wants to send more than 4 digits of OTP.

**Comment by teamseamive** [comment]
Had the reference from https://github.com/craftsys/msg91-php#configuration showing to add 'otp_length' in config/services under msg91.php

**Comment by teamseamive** [comment]
Seems to stop working with the latest laravel 8. Can this be updated to the latest on https://docs.msg91.com/p/tf9GTextN/e/tWCcnGyFqX/MSG91

Also, no response when using resend() or verify() OTP.

@craftsys

**Comment by sudkumar** [comment]
Out of station at the moment. 
In the meantime, please debug and provide any more information if available.
