### ISSUE TITLE
It is working with queue

### ISSUE THREAD

**Issue by milandrcsystems** [craftsys/msg91-laravel#9]
While I am trying to send SMS using this package I got following error:

`Class 'Craftsys\Msg91\Facade\Msg91' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Craftsys\\Msg91\\Facade\\Msg91' not found at /var/www/html/laravel/project/app/Common/Msg91Gateway.php:40)`

**Comment by sudkumar** [comment]
Can you please provide a reproduction example code for this issue?

**Comment by sudkumar** [comment]
@milandrcsystems didn't get any response. 😐

I am assuming the issue is resolved . Feel free to reopen with an issue reproduction example.
